In [37]:
import numpy as np
import pandas as pd

In [63]:
# lire le fichier de sequence et stock les 5 sequence
with open ('sequences.fasta','r') as seq :
    lines = seq.readlines()

sequences = []
s = ''
for line in lines:

    if line == '\n' or line == '':
        sequences.append(s)
        s = ''
    elif line[0] != '>' :
        s += line.strip('\n')
sequences.append(s)
print(sequences)

['MGEIGFTEKQEALVKESWEILKQDIPKYSLHFFSQILEIAPAAKGLFSFLRDSDEVPHNNPKLKAHAVKVFKMTCETAIQLREEGKVVVADTTLQYLGSIHLKSGVIDPHFEVVKEALLRTLKEGLGEKYNEEVEGAWSQAYDHLALAIKTEMKQEES', 'MEKVPGEMEIERRERSEELSEAERKAVQATWARLYANCEDVGVAILVRFFVNFPSAKQYFSQFKHMEEPLEMERSPQLRKHACRVMGALNTVVENLHDPEKVSSVLSLVGKAHALKHKVEPVYFKILSGVILEVIAEEFANDFPPETQRAWAKLRGLIYSHVTAAYKEVGWVQQVPNATTPPATLPSSGP', 'MVLSAADKNNVKGIFTKIAGHAEEYGAETLERMFTTYPPTKTYFPHFDLSHGSAQIKGHGKKVVAALIEAANHIDDIAGTLSKLSDLHAHKLRVDPVNFKLLGQCFLVVVAIHHPAALTPEVHASLDKFLCAVGTVLTAKYR', 'MGLSDGEWQLVLNVWGKVEADIPGHGQEVLIRLFKGHPETLEKFDKFKHLKSEDEMKASEDLKKHGATVLTALGGILKKKGHHEAEIKPLAQSHATKHKIPVKYLEFISECIIQVLQSKHPGDFGADAQGAMNKALELFRKDMASNYKELGFQG', 'MERLESELIRQSWRAVSRSPLEHGTVLFSRLFALEPSLLPLFQYNGRQFSSPEDCLSSPEFLDHIRKVMLVIDAAVTNVEDLSSLEEYLATLGRKHRAVGVRLSSFSTVGESLLYMLEKCLGPDFTPATRTAWSQLYGAVVQAMSRGWDGE']


In [68]:
# lire le fichier de score d'alignement et creer la matrice de score utilise
with open('BLOSUM62.txt', 'r') as scores:
    lines = scores.readlines()

kv = dict()
scoreMatrix = []

for line in lines:
    # create a key:pair value for each possible AA that are indicated in the first row
    if line[0] == ' ':
        x = line.replace(' ', '')
        for i in range(len(x)):
            kv.update({x[i]: i})

    #Create the score matrix from the blosum file without the header and the first colum
    #Square matrix starting at 0,0 for A,A
    else:
        values = line[2:].replace(' ', ',').replace(',,', ',').strip(',\n')
        if values[0] == ',':
            values = values[1:]
        row = values.split(',')
        scoreMatrix.append(row)


In [69]:
# Trouver le score d'alignement dans notre fonction
def score(char1, char2):
    key1 = kv.get(char1)
    key2 = kv.get(char2)

    result = int(scoreMatrix[key1][key2])
    return result

In [70]:
# Alignement global entre sequences
def global_alignment (s1,s2):
    a = 10
    b = 1

    # Matrix initialisation
    V = np.ones(shape=(len(s2)  +1, len(s1) + 1)) * np.NINF
    G = np.ones(shape=(len(s2) + 1, len(s1) + 1)) * np.NINF
    F = np.ones(shape=(len(s2) + 1, len(s1) + 1)) * np.NINF
    E = np.ones(shape=(len(s2) + 1, len(s1) + 1)) * np.NINF

    #Initial conditions
    G[0][0] = 0

    for i in range(len(s2)+1):
        V[i][0] = -(a + b * i)
        F[i][0] = -(a + b * i)

    for j in range(len(s1)+1):
        V[0][j] = -(a + b * j)
        E[0][j] = -(a + b * j)

    for r in range(1, len(s2)+1):
        for c in range(1,len(s1)+1):

            # Character looked at
            char1 = s1[c - 1]
            char2 = s2[r - 1]

            # update G matrix
            G[r][c] = V[r - 1][c - 1] + score(char1, char2)

            # update E matrix
            v1 = E[r][c-1]
            v2 = V[r][c-1] - a
            E[r][c] = max(v1, v2) - b

            # update F matrix
            v1 = F[r-1][c]
            v2 = V[r-1][c] - a
            F[r][c] = max(v1, v2) - b

            # update V matrix
            V[r][c] = max(G[r][c], E[r][c], F[r][c])

    return V[len(s2)][len(s1)]

In [71]:
a1 = "MGEIGFTEKQEALVKESWEILKQDIPKYSLHFFSQILEIAPAAKGLFSFLRDSDEVPHNNPKLKAHAVKVFKMTCETAIQLREEGKVVVADTTLQYLGSIHLKSGVIDPHFEVVKEALLRTLKEGLGEKYNEEVEGAWSQAYDHLALAIKTEMKQEES"
a2 = "MEKVPGEMEIERRERSEELSEAERKAVQATWARLYANCEDVGVAILVRFFVNFPSAKQYFSQFKHMEEPLEMERSPQLRKHACRVMGALNTVVENLHDPEKVSSVLSLVGKAHALKHKVEPVYFKILSGVILEVIAEEFANDFPPETQRAWAKLRGLIYSHVTAAYKEVGWVQQVPNATTPPATLPSSGP"
print(global_alignment(a1,a2))
print(global_alignment(a2,a1))

46.0
46.0


In [72]:
# trouver la matrice des score de similarité
sim_mat = np.zeros(shape=(len(sequences), len(sequences)))
for i in range(len(sequences)):
    for j in range(len(sequences)):
        sim_mat[i][j] = global_alignment(sequences[i],sequences[j])
print(sim_mat)

[[798.  46.  13.  30.  72.]
 [ 46. 973.  87. 136.  67.]
 [ 13.  87. 727.  76.  13.]
 [ 30. 136.  76. 799.  14.]
 [ 72.  67.  13.  14. 762.]]


In [ ]:
# deduire la sequence centrale parmis les mots

In [ ]:
# Construire l'alignement multiple avec la methode centrales

In [ ]:
# donner le score SP de l'alignement etoile

In [ ]:
# Donnez la sequence consensus Z de l'alignement